repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2 # ruffバージョン
    hooks:
      # リンターの実行
      - id: ruff
        name: lint with ruff
      - id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]
      # フォーマッターの実行
      - id: ruff-format
        name: format with ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # mypyバージョン
    hooks:
      # タイプチェックの実行
      - id: mypy
        name: type check with mypy
